version: '3'

services:
  nginx:
    container_name: symfony6-nginx
    build:
      context: ./.docker/nginx
      args:
        APP_ENV: ${APP_ENV}
        APP_PHP_FPM: symfony6-php-fpm
    ports:
      - ${APP_WEB_PORT}:80
    depends_on:
      - mysql
      - php_fpm
    working_dir: /app
    volumes:
      - ./:/app:rw
    restart: always

  php_fpm:
    container_name: symfony6-php-fpm
    build:
      context: ./.docker/php-fpm
      args:
        APP_ENV: ${APP_ENV}
    volumes:
      - ./:/app:rw
      - ./var/log:/app/var/log:rw
    working_dir: /app
    restart: always

  mysql:
    container_name: ${MYSQL_HOST}
    image: mysql:5.7
    ports:
      - "53306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root_password}
      MYSQL_DATABASE: ${MYSQL_DB:-app}
      MYSQL_USER: ${MYSQL_USER:-app}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-!ChangeMe!}
    restart: always

  phpmyadmin:
    container_name: symfony6-phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
      - '59083:80'
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
    depends_on:
      - mysql
    restart: always
